# Generated by Django 3.1.3 on 2020-11-26 10:31

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='member_image',
            field=models.ImageField(default='', upload_to=members.models.image_upload),
            preserve_default=False,
        ),
    ]
