# Generated by Django 3.1.3 on 2020-11-29 08:36

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20201129_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='member_image',
            field=models.ImageField(blank=True, null=True, upload_to=members.models.image_upload),
        ),
        migrations.AlterField(
            model_name='members',
            name='member_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
