# Generated by Django 3.1.3 on 2020-12-09 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0004_auto_20201129_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='auth.user'),
            preserve_default=False,
        ),
    ]
